Attacque Supérior is a third-party logic
extension based on OpenRA.

The plugin is maintained by
 * Gyula Zimmermann (Graion Dilach)

 Authors of logics:
 * Gyula Zimmermann (Graion Dilach)
   > everything unless listed

 * Andre Mohren (IceReaper)
   > KKND laser implementation

 * Boolbada/forcecore
   > RadBeam implementation
   > ProvidesAIPrerequisite
   > initial AIDeployHelper
   > GrantStackableConditionOnFire aka Gattling
   > ArcRenderable
   > Nydus tunnel logic
   > mind control traits
   > Berserkable
   > TintedCells (former radioactivity)
   > PointDefense logic

 * Holloweye
   > SmokeParticle(Emitter) basic implementation

 * lucasss
   > (Gives)ProximityBounty basic implementation

 * Matthias Mailänder (Mailaender)
   > WithExitOverlay

 * Martin Lang (Gerseras/Seraphinexxx)
   > DelayedWeapon system

 * Mustafa Alperen Seki (MustaphaTR)
   > ProductionCost/TimeMultiplier
   > mindcontrol traits cleanup
   > /taunt command
   > Intelligence logic
   > Infect logic

 * Pavel Penev (penev92)
   > PaletteFromJasc32File - base JASC palette parser

 * Sean Hunt (coppro)
   > Chrono Miner implementaion (ChronoResourceDelivery)

 * jrb0001
   > AmmoPool support for ExplodeWeapon

 * Wojciech Walaszek (Voidwalker)
   > TeleportNetwork maintaince
   > WarheadTrailProjectile
   > TintedCells maintaince
   > TurnOnIdle

 Authors of documents used in this plugin:
  * Apollo
   > Jasc 32bit format idea

The project owes thanks for OpenRA for it's modularity
which allows this project to exist in the first place.

Also thanks for you, the user for using this project.
